# Generated by Django 5.0.6 on 2024-06-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("наличными", "наличными"), ("переводом", "переводом")],
                max_length=10,
            ),
        ),
    ]
