# Generated by Django 5.0.6 on 2024-06-05 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_amount_alter_payment_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
