# Generated by Django 5.0.6 on 2024-06-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_options_payment_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("наличными", "наличными"), ("переводом", "переводом")],
                default="переводом",
                max_length=10,
            ),
        ),
    ]
