# Generated by Django 5.0.6 on 2024-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("наличными", "наличными"), ("переводом", "переводом")],
                default="переводом",
                help_text="Выберите метод оплаты",
                max_length=10,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
